### ISSUE TITLE
PEP8

### ISSUE THREAD

**Issue by aj-hitchins** [fmitchell259/NetworkSimulator#1]
Hi Frank,

A little pointer to [PEP8 - Syle guide for Python](https://www.python.org/dev/peps/pep-0008/) which contains best practise understood in the community around styling such as whitespace, variable and class name structures, and more!

Best,

AJ

**Comment by fmitchell259** [comment]
Hi AJ,

Many thanks, as a novice python programmer, resources like this are very helpful. 

Thanks again.
Frank
